# AQ-用户标签系统配置
app:
  name: "AQ-用户标签系统"
  version: "1.0.0"
  debug: true

llm:
  provider: "deepseek"
  model: "deepseek-reasoner"
  api_key: "sk-dda1273e7fe940478167bc1629cec0d4"  # DeepSeek API key
  base_url: "https://api.deepseek.com"
  max_tokens: 1000
  temperature: 0.3

storage:
  type: "local"
  base_path: "./user_data"
  backup_enabled: true
  cleanup_days: 90
